services:
  dvacoo:
    image: dextre1480/dva:1.1
    container_name: dva
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - dvacoo-net

networks:
  dvacoo-net:
    driver: bridge


